import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState } from 'react';
import { Provider } from 'starknet';
import { ColorMix } from '../types/types';
import { ColorResult, RgbColor, SketchPicker } from '@hello-pangea/color-picker';
import { useMixingTwoColors } from '../hooks/mixing';
import ColorBlock from '../components/ColorBlock';

export default function Home() {
  const [myColors, setMyColors] = useState<any[]>([]);
  const [color1, setColor1] = useState<RgbColor>();
  const [color2, setColor2] = useState<RgbColor>();
  const [ratio, setRatio] = useState(0);

  const mixColor = () => {
    if (color1 && color2 && ratio !== undefined)
      useMixingTwoColors(color1, color2, ratio).then((res) => {
        setMyColors([...myColors, res]);
      });
  };

  console.log('color1', color1);
  console.log('color2', color2);
  console.log('myColors', myColors);

  const handleChange = (id: number, color: ColorResult, event: any) => {
    if (id === 1) setColor1(color.rgb);
    if (id === 2) setColor2(color.rgb);
  };

  return (
    <>
      <Head>
        <title>Mixing Colors</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div>
          <div className={styles.section1}>
            <h1>Mix colors</h1>
            <p>Enter 2 colors and a ratio to mix them</p>
            <div className={styles.inputs}>
              <div className={styles.inputColor}>
                <h2>Color 1</h2>
                <SketchPicker onChange={(color, event) => handleChange(1, color, event)} color={color1} />
              </div>

              <div className={styles.inputColor}>
                <h2>Color 2</h2>
                <SketchPicker onChange={(color, event) => handleChange(2, color, event)} color={color2} />
              </div>

              <div className={styles.inputColor}>
                <h2>Ratio</h2>
                <input
                  value={ratio}
                  type='number'
                  min={0}
                  max={1}
                  step='0.01'
                  onChange={(e) => {
                    setRatio(Number(e.target.value));
                  }}
                  className={styles.input}
                />
                <button onClick={() => mixColor()}>Mix colors</button>
              </div>
            </div>
          </div>

          <div className={styles.section2}>
            <>
              <h1>Mixing results</h1>
              <div style={{ display: 'flex', flexDirection: 'row', flexWrap: 'wrap' }}>
                {myColors &&
                  myColors.length > 0 &&
                  myColors.map((color, index) => {
                    return <ColorBlock {...color} key={index} />;
                  })}
              </div>
            </>
          </div>
        </div>
      </main>
    </>
  );
}
